In [1]:
import torch
from nn.linear import Linear 
from nn.loss import MSELoss

In [2]:
x = torch.empty((5)).normal_()
y = torch.empty((2)).normal_()

In [3]:
lr=0.01

In [4]:
mod_ours = Linear(5, 2)

In [5]:
mod_theirs = torch.nn.Linear(5, 2)

In [6]:
mod_theirs.weight.data, mod_theirs.bias.data = mod_ours.param()

In [7]:
opt_theirs = torch.optim.Adam(mod_theirs.parameters(), lr=lr, 
                             betas=(0.9, 0.999),
                             eps=1e-8)
opt_ours = 'adam'

In [8]:
loss_fn_ours = MSELoss()
loss_fn_theirs = torch.nn.MSELoss()

In [9]:
mod_theirs.zero_grad()

In [10]:
out_ours = mod_ours(x)

RuntimeError: self must be a matrix

In [11]:
out_theirs = mod_theirs(x)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x5 and 2x5)

In [12]:
loss_ours = loss_fn_ours(out_ours, y)

NameError: name 'out_ours' is not defined

In [13]:
loss_theirs = loss_fn_theirs(out_theirs, y)

In [14]:
dy = loss_fn_ours.backward()
mod_ours.backward(dy)

tensor([ 1.0206,  2.9472, -1.3874, -1.2004,  3.0741])

In [15]:
loss_theirs.backward()

In [16]:
opt_theirs.step()

In [17]:
mod_ours._update_params(optim=opt_ours, lr=lr)

In [18]:
# check if the weights + biases are the same 

In [19]:
mod_ours.cache['w']

tensor([[ 0.4864,  0.3819, -0.2643, -0.5969,  1.2572],
        [ 0.3489, -1.7624,  0.5740, -0.4616,  0.2283]])

In [20]:
mod_ours.cache['b']

tensor([0.2172,    nan])

In [21]:
mod_theirs.weight

Parameter containing:
tensor([[ 0.4864,  0.3819, -0.2643, -0.5969,  1.2572],
        [ 0.3489, -1.7624,  0.5740, -0.4616,  0.2283]], requires_grad=True)

In [22]:
mod_theirs.bias

Parameter containing:
tensor([0.2172,    nan], requires_grad=True)